# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 03:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=30)),
                ('sender_department', models.CharField(max_length=30)),
                ('post_on', models.DateTimeField()),
                ('content', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('Computer Science', 'CS'), ('Computer Engineering', 'CE'), ('Civil Engineering', 'Civil'), ('Electrical and Electronics Engineering', 'EE'), ('Environment Engineering', 'ENE'), ('Chemical Engineering', 'CHE'), ('Mechanical Engineering', 'ME'), ('Geomatics Engineering', 'GE'), ('Biotechnology', 'BT'), ('Pharmacy', 'BP'), ('Environment Science', 'ES'), ('Applied Physics', 'AP'), ('Human Biology', 'HB'), ('Law', 'Law')], max_length=20)),
                ('semester', models.CharField(choices=[('First', '1st'), ('Second', '2nd'), ('Third', '3rd'), ('Fourth', '4th'), ('Fifth', '5th'), ('Sixth', '6th'), ('Seventh', '7th'), ('Eighth', '8th'), ('Ninth', '9th'), ('Tenth', '10th')], max_length=20)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Notice.Notices')),
            ],
        ),
    ]
